#!/bin/sh

shift

REVISION="${1:-"${CI_COMMIT_ID}"}"
shift

if [ "${REVISION}" = "" ]; then
  script=$(basename "${0}")
  echo "Usage: ${script} <revision> [extra_args]"
  echo "  revision - the revision for this deployment (required)"
  echo "  extra_args - if supplied, this is passed directly to kubernetes-deploy"
  exit
fi

if echo "${CI_COMMIT_MESSAGE}" | fgrep -qi "[skip deploy]"; then
  echo "Skipping deployment."
  exit
fi

context="${CONTEXT:-"aws"}"
namespace="overseer"
template_dir="k8s"

export REVISION
export KUBECONFIG="${KUBECONFIG:-"${HOME}/.kube/config"}"

kubernetes-deploy "${namespace}" "${context}" \
  --template-dir="${template_dir}" \
  "$@"
