#!/bin/sh

shift

REVISION="${1:-"${CI_COMMIT_ID}"}"
shift

if [ "${REVISION}" = "" ]; then
  script=$(basename "${0}")
  echo "Usage: ${script} <revision> [extra_args]"
  echo "  revision - the revision for this deployment (required)"
  echo "  extra_args - if supplied, this is passed directly to kubernetes-deploy"
  exit
fi

if echo "${CI_COMMIT_MESSAGE}" | fgrep -qi "[skip deploy]"; then
  echo "Skipping deployment."
  exit
fi

context="${CONTEXT:-"aws"}"
namespace="overseer"
template_dir="k8s"

export REVISION
export KUBECONFIG="${KUBECONFIG:-"${HOME}/.kube/config"}"

cluster_conf=/tmp/cluster.tfstate.json
ssl_conf=/tmp/ssl.tfstate.json
output_bindings=/tmp/bindings.json

aws s3 cp s3://hippware-terraform-state/cluster/terraform.tfstate ${cluster_conf}
aws s3 cp s3://hippware-terraform-state/ssl/terraform.tfstate ${ssl_conf}

jq -s '[.[].outputs] | add' ${cluster_conf} > ${output_bindings}

kubernetes-deploy "${namespace}" "${context}" \
  --template-dir="${template_dir}" \
  --bindings=@${output_bindings} \
  "$@"
