apiVersion: v1
kind: Service
metadata:
  name: overseer-webhooks
  namespace: overseer
  labels:
    app: overseer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '300'
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: '5'
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: 'hippware-logs'
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: 'overseer/elb'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'tcp'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:acm:us-west-2:773488857071:certificate/0342584c-d783-4f1f-bfb1-f437c11b53e9'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
  selector:
    app: overseer
  type: LoadBalancer
