apiVersion: v1
kind: Service
metadata:
  name: overseer-webhooks
  namespace: overseer
  labels:
    app: overseer
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: overseer
  type: NodePort
